# Generated by Django 6.1.1 on 2026-10-02 06:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeSonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=60)),
                ('notas', models.TextField(blank=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_tentativa', models.DateField()),
                ('visitado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'viaje soñado',
                'verbose_name_plural': 'viajes soñados',
                'ordering': ['fecha_tentativa'],
            },
        ),
    ]
